version: '3.8'

services:
  rabbitmq_3_12_9:
    image: rabbitmq:3.12.9-management-alpine
    container_name: rabbitmq_3_12_9
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  rabbitmq_3_13_0:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbitmq_3_13_0
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
